Cu 864dpwv8d criar e setupar inicialmente o bosch planner app igor oliveira
ets-einer/einer pull request #22
Opened 2023-01-17 18:23 UTC by iguoliveira

##### Description of changes

- [x] Why (Why did you make this pull request): Initial setup of planner app (server and web)
- [x] Brief description of the changes: Modified web and server templates to fulfill initial planner's necessities
- [x] Possible breakouts (Possible places where things could break): Error with .env file, not locating linking path. A possible local error.

2023-01-17 18:47 UTC, vitormiura requested changes
**Forgot to change web and server ports, for server, need to change the PORT in index.ts to process.env.VITE_WEB_PLANNER_PORT | | 3002.**
![image](https://user-images.githubusercontent.com/93823300/212983854-7a725ba6-b0f2-4b30-8e63-52066261e2e0.png)
**Is good too to setup cors too with planner web env, just add "VITE_WEB_PLANNER_PORT" instead of "VITE_WEB_TEMPLATE_PORT"**
![image](https://user-images.githubusercontent.com/93823300/212984358-7f5283b5-ed86-488c-9cf7-12af6a1f3468.png)
**In web is necessary to change the port too, remove "VITE_WEB_TEMPLATE_PORT" and add  "VITE_WEB_PLANNER_PORT"**

2023-01-17 18:54 UTC, vitormiura commented on apps/server-planner/logger.ts
> +export const logger = new Logger("SERVER-TEMPLATE");
needs to change to "SERVER-TEMPLATE" to PLANNER

2023-01-21 13:59 UTC, iguoliveira commented
> **Forgot to change web and server ports, for server, need to change the PORT in index.ts to process.env.VITE_WEB_PLANNER_PORT | | 3002.** ![image](https://user-images.githubusercontent.com/93823300/212983854-7a725ba6-b0f2-4b30-8e63-52066261e2e0.png) **Is good too to setup cors too with planner web env, just add "VITE_WEB_PLANNER_PORT" instead of "VITE_WEB_TEMPLATE_PORT"** ![image](https://user-images.githubusercontent.com/93823300/212984358-7f5283b5-ed86-488c-9cf7-12af6a1f3468.png) **In web is necessary to change the port too, remove "VITE_WEB_TEMPLATE_PORT" and add "VITE_WEB_PLANNER_PORT" in vite.config.ts file** ![image](https://user-images.githubusercontent.com/93823300/212985217-b9b29aab-f536-4909-9519-eacda1fecfd8.png)

First of all, thanks for the clear instructions to how fix the bugs
![image](https://user-images.githubusercontent.com/57506257/213870227-408d2edf-7867-407a-9b8f-7b9c2a8af320.png)
![image](https://user-images.githubusercontent.com/57506257/213870233-e91b293f-78cf-490b-845a-91189676a6e5.png)
Probably just a misspell, but in index.ts, needed to change from template to service-planner in PORT, for services run in 4002, however, working fine here

2023-01-22 18:35 UTC, abehidek commented
CI passing now, needed to fix some imports, environment variables and config
I tested on my machine and it seems it's working fine on a docker dev environment.

Apparently, CI was failing before cause `web-planner` was importing `AppRouter` type from `server-template`, and that seems to trigger a build from `server-template`, however, `pnpm run build` cmd don't cover `server-template` because it does not have a `scripts` property in it's `package.json` file (it's named `_scripts` intentionally to not trigger build), I fixed the import to point to `server-planner` instead, then after fixing the unused variable by prefixing it with `_`, the build command seems to be working nicely.

I also did change the `.gitignore` file to ignore only the root dir `.env`file by prefixing it with `/`, this makes possible to commit the `.env` symlink files located inside the apps without forcing it.

Other than that, I also fixed some `cors` config to point to `web-planner` url instead of `web-template` url, and made the trpc client on `web-planner` point to `server-planner` url instead of `server-template` url

2023-01-22 18:36 UTC, abehidek approved these changes
Apparently it works fine now

2023-01-22 18:37 UTC, abehidek commented
@vitormiura @viktormarinho please review it once again to see if there's any other fix to do.

2023-01-22 21:03 UTC, vitormiura approved these changes
Everything working fine, merging rn.

2023-01-22 21:03 UTC, merged