Cu 864dvj0b8 nav bar global julia
ets-einer/einer pull request #45
Opened 2023-02-08 13:22 UTC by juhelena

##### Description of changes

- [ ] Why (Why did you make this pull request): Navbar global finalized

- [ ] Brief description of the changes: Inclusion of images and change in menu hover
- [ ] Possible breakouts (Possible places where things could break):

2023-02-08 13:42 UTC, vitormiura commented
do not merge @abehidek @iguoliveira @viktormarinho, adding component class variants soon.

2023-02-14 16:39 UTC, iguoliveira reviewed
I'll start adding class variants to this component. In the next daily we can discuss about these changes. 😁

2023-02-15 13:12 UTC, iguoliveira approved these changes
Seems fine to merge!

2023-02-15 13:27 UTC, viktormarinho requested changes

2023-02-15 13:27 UTC, viktormarinho commented on apps/web-planner/src/pages/index.tsx
> +import { NavBar } from "ui/base/NavBar";
This export should be coming from 'ui' too! dont know if you are not exporting it from index or just imported that way by accident

2023-02-15 13:27 UTC, viktormarinho commented on package.json
> +    "clsx": "^1.2.1"
This should be removed and installed in the UI Package. 
after doing this, please do pnpm install again so the pnpm-lock.yml is updated

When you are installing packages, use pnpm add --filter <PACKAGE_NAME>

It wil prompt you and warn before installing global dependencies, you can only do it when 
passing the -w flag, so read the warning messages fully so you dont need to change dependency location again

2023-02-15 13:36 UTC, vitormiura approved these changes
just tested the component, and its working fine, just need to add clsx to ui pkg as @viktormarinho described above.

2023-02-15 13:43 UTC, iguoliveira commented on package.json
> +    "clsx": "^1.2.1"
Thanks for warning! 😁

2023-02-15 13:59 UTC, viktormarinho approved these changes
Looks ok now!

2023-02-15 14:00 UTC, merged