Cu 864dtv11y poc to einer iguoliveira
ets-einer/einer pull request #70
Opened 2023-03-02 13:54 UTC by gustavobaltazar

##### Description of changes

- [x] Why (Why did you make this pull request): to implement the poc on einer
- [x] Brief description of the changes: Test added and backend refactor & front end 
- [x] Possible breakouts (Possible places where things could break):Already tested, but possible with data send

2023-03-02 19:09 UTC, iguoliveira commented on apps/server-planner/prisma/schema.prisma
> +
?

2023-03-02 19:29 UTC, iguoliveira commented on apps/server-planner/src/routers/card.ts
> +          message: "Cannot to create card!",
to

2023-03-02 19:42 UTC, iguoliveira requested changes
need to fix somethings

2023-03-02 19:42 UTC, iguoliveira commented on apps/server-planner/src/routers/card.ts
> +            title: input.title,
need to contain all fields, if the user want to create a complete card

2023-03-03 11:16 UTC, gustavobaltazar commented on apps/server-planner/src/routers/card.ts
> +            title: input.title,
Fixed 👍

2023-03-03 11:19 UTC, vinicius-prates approved these changes
Nice one!

2023-03-03 11:19 UTC, iguoliveira approved these changes
🚀

2023-03-03 11:19 UTC, merged